# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mic_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mic_window(object):
    def setupUi(self, Mic_window):
        Mic_window.setObjectName("Mic_window")
        Mic_window.resize(714, 462)
        self.centralwidget = QtWidgets.QWidget(Mic_window)
        self.centralwidget.setObjectName("centralwidget")
        self.Img_label = QtWidgets.QLabel(self.centralwidget)
        self.Img_label.setGeometry(QtCore.QRect(0, 0, 711, 501))
        self.Img_label.setAutoFillBackground(False)
        self.Img_label.setStyleSheet("\n"
"image: url(:/newPrefix/Images/mic_background.jpg);")
        self.Img_label.setText("")
        self.Img_label.setScaledContents(False)
        self.Img_label.setWordWrap(False)
        self.Img_label.setObjectName("Img_label")
        self.label_listening = QtWidgets.QLabel(self.centralwidget)
        self.label_listening.setGeometry(QtCore.QRect(260, 170, 241, 111))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(28)
        self.label_listening.setFont(font)
        self.label_listening.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_listening.setObjectName("label_listening")
        self.Back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Back_btn.setGeometry(QtCore.QRect(600, 350, 61, 41))
        self.Back_btn.setStyleSheet("background-color: transparent;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: skyblue;\n"
"padding: 4px;\n"
"color: rgb(85, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.Back_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_prefix/Icons/back-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back_btn.setIcon(icon)
        self.Back_btn.setIconSize(QtCore.QSize(30, 49))
        self.Back_btn.setObjectName("Back_btn")
        Mic_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Mic_window)
        self.statusbar.setObjectName("statusbar")
        Mic_window.setStatusBar(self.statusbar)

        self.retranslateUi(Mic_window)
        QtCore.QMetaObject.connectSlotsByName(Mic_window)

    def retranslateUi(self, Mic_window):
        _translate = QtCore.QCoreApplication.translate
        Mic_window.setWindowTitle(_translate("Mic_window", "MainWindow"))
        self.label_listening.setText(_translate("Mic_window", "LISTENING"))
import icon_rc
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mic_window = QtWidgets.QMainWindow()
    ui = Ui_Mic_window()
    ui.setupUi(Mic_window)
    Mic_window.show()
    sys.exit(app.exec_())
